import assert from 'node:assert/strict';import test from 'node:test';import {FishingRound} from '../src/systems/FishingRound.ts';import {ProgressStore} from '../src/systems/ProgressStore.ts';
const advance=(r,n)=>{for(let i=0;i<n/.025;i++)r.update(.025)};
function fight(index,steer=true){let n=0;const r=new FishingRound(()=>[.5,.5,(index+.2)/4][n++%3]);r.start('battle');r.step('bite');r.tap();let held=true,rests=0,pulls=0;for(let i=0;i<3600&&r.phase==='reel';i++){if(r.tension>.76){held=false;rests++;}else if(r.tension<.28)held=true;r.holdReel(held);if(steer){r.steer(r.desiredDirection);if(r.desiredDirection)pulls++;}r.update(.025);}return{r,rests,pulls};}
test('Cast and a forgiving hook window lead to a real battle',()=>{const r=new FishingRound(()=>.5);r.start('one');r.tap();advance(r,2);assert.equal(r.phase,'wait');while(r.phase==='wait')r.update(.025);assert.equal(r.phase,'bite');advance(r,3.2);r.tap();assert.equal(r.phase,'reel');assert.equal(r.catchKind,'fish');});
test('All four fish can be landed with hold, countersteer and release in a short round',()=>{for(let i=0;i<4;i++){const {r,rests,pulls}=fight(i);assert.equal(r.phase,'catch');assert.ok(rests>0);assert.ok(pulls>0);assert.ok(r.fightTime>8&&r.fightTime<40);r.step('release');advance(r,1.1);assert.equal(r.phase,'idle');}});
test('Holding forever loses the fish; resting recovers tension; tapping never skips battle',()=>{const r=new FishingRound(()=>.5);r.start('two');r.step('reel');for(let i=0;i<50;i++)r.tap();assert.equal(r.progress,.12);r.holdReel(true);advance(r,5);assert.equal(r.phase,'reel');const high=r.tension;r.holdReel(false);advance(r,1);assert.ok(r.tension<high-.3);r.holdReel(true);advance(r,30);assert.equal(r.phase,'miss');assert.match(r.missReason,/Let go/);});
test('Missed hooks and abandoned fights never award an automatic catch',()=>{const r=new FishingRound(()=>.3);r.start('three');r.step('bite');advance(r,3.8);assert.equal(r.phase,'miss');r.step('reel');advance(r,91);assert.equal(r.phase,'miss');});
test('Countersteering rewards active play while no steering remains forgiving',()=>{for(let i=0;i<4;i++){const active=fight(i),simple=fight(i,false);assert.equal(simple.r.phase,'catch');assert.ok(active.r.fightTime<simple.r.fightTime);}});
test('Releasing controls and leaving reset all held inputs',()=>{const r=new FishingRound(()=>.5);r.start('four');r.step('reel');r.holdReel(true);r.steer(1);r.releaseControls();assert.equal(r.reeling,false);assert.equal(r.direction,0);r.holdReel(true);r.step('idle');assert.equal(r.reeling,false);});
test('Fishing uses the existing collection and an idempotent receipt',()=>{let raw=null;const repo={read:()=>raw,write:v=>raw=v};const p=new ProgressStore(repo,()=>0);const receipt=p.catchFishingSquishy('catch-one');assert.equal(receipt.isNew,true);assert.equal(p.data.collection[receipt.dumplingId],1);assert.deepEqual(p.catchFishingSquishy('catch-one'),receipt);const q=new ProgressStore(repo,()=>0);assert.equal(q.catchFishingSquishy('catch-two').isNew,false);assert.equal(q.data.collection[receipt.dumplingId],2);assert.equal(q.data.balance,0);assert.equal(q.data.boxes.length,0);});
test('Failed writes do not expose an uncommitted fishing reward',()=>{const p=new ProgressStore({read:()=>null,write:()=>{throw Error('full')}},()=>0);assert.throws(()=>p.catchFishingSquishy('catch'),/Unable to save/);assert.deepEqual(p.data.collection,{});});
